name: CI - Because Ship Happens

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # GitHub’s greatest hits: The Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # Node setup, because we’re not savages
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install those precious dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests, make it rain coverage
      - name: Run tests with coverage
        run: npm test -- --coverage

      # Drumroll please... time for Codecov to flex
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ 4193e058-2df8-45d5-b71d-b63a97462adb }}
          slug: CassieMarie0728/creative-command-biker-edition

      # Bonus points: fail if coverage is missing, because we have standards
      - name: Check for coverage report (don’t let it be empty, rookie!)
        run: |
          if [ ! -f coverage/lcov.info ]; then
            echo "No coverage report found! You call that testing?!"
            exit 1
          fi
